name: "Build project dependencies"

runs:
    using: "composite"
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
              python-version: "3.12"
        - name: Setup Poetry
          run: pip install -U pip wheel "poetry==1.8.3"
          shell: bash
        - name: Install dependencies
          run: poetry install
          shell: bash
