name: "Device Monitor Workflow"

on:
    push:
    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Build project dependencies
              uses: ./.github/workflows/composite/dependencies
            - name: Ruff
              run: poetry run ruff check
              shell: bash
            - name: MyPy
              run: poetry run mypy device_monitor
              shell: bash
    
    test:
        runs-on: ubuntu-latest
        needs:
            - lint
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Build project dependencies
              uses: ./.github/workflows/composite/dependencies
            - name: PyTest
              run: poetry run pytest --cov=device_monitor --cov-report=json tests
              shell: bash
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
